#Embedded image created from /home/moncs/ddube1/Atom3/Kernel/Constraints/constraint.gif
#Done with imageEmbedder 1.0 utility img2pytk.py from
#  http://www.3dartist.com/WP/python/pycode.htm#img2pytk

import Tkinter as tk
root = tk.Tk()

img00 = tk.PhotoImage(format='gif',data=
             'R0lGODlhHgCWAPcAAOvr/8z43dv85sHy2VdnWVd3WavVtWSZaPb2/9zc/le3'
            +'Wt/f/tra/uzs/4rxkWJ5Z8Ld6sLozoS4dF1wYMvq0tX03W2uXp3Dppi2ntTU'
            +'/mOmZnvNhpTFnODg/u/v/2e6alaYZNjY/uz+8ePj/niWenmRfuH96rzbxb7k'
            +'4lGbVEiDWoahiTxzV4y7l5i9oFaFYubm/8X22tbW/sn329X74lrCXqDMrJ3Y'
            +'p6nMtFY1WtLS/mbEbVRdVuX+7aW9r+Tk/6rkt2F7XXK0dYa8jl2dX+np/1eh'
            +'YL/w2VZAW/Dw/17NYb3u2n2og1xMYGybddDQ/mRcarXYusL02Wn/bNz1483S'
            +'+1GhU168YoTFhFjyWGrLcneIfouqlPH+9Wmzb3SqdlulXY2RaoqblHPxekui'
            +'V0VhS2ytdKTdrUucS9H64E6nT1uKX4/Sl1acWY3dlL3q3LHhvLv4xVOTVXu5'
            +'gcrV9kmLYlOMVK7cwW2IdpawnUVYSEN7WVuWXWPTaXTofbrjw4zIlsvx1VKU'
            +'XpnxoW3ZcVqAXGFqZYKZiGTlaFysUbTlxU6eW0uZVej+7ka3X2p7cN796Fjc'
            +'XHW1Z0uIS2GNY0WTUVWFWmWEammgUkyTUMPezMXa722Mb0yUXFOpX2mGbKP9'
            +'q9Tr3EdES3WTTb3tyHGFTVmZc1uvXmWQammXTT+LVnuiVHeYUYPTiW/Ac5Gb'
            +'mnKYZGiMS4R6WVaYTFakWE6FUoSKjkpzTMbw077hx3F2e0eUWsDh5lykUrvu'
            +'0r3n309EUVSLXFWtV2hscleZVmF/Zb3r27LPvHeKUOb26kxbT/////n5//Pz'
            +'//T0//7+//r6//z8//j4//X1//39//v7//Ly/+P964C5lZjRja2sluD55lWW'
            +'VlmOWUeSaNbW/cfY8tDQ+J3MoZvctFJRUuP56cDPsuX46XCEctj75EqwTouk'
            +'aVOyUVWjdliCUHbXeobJe2GEX1/xY2qqgW+kckGeU3V2gVBnU2uAZ2yQaVJ9'
            +'VI2Nl2LbW7HFx0+/UrfjyiH5BAAAAAAALAAAAAAeAJYAAAj/AJ9RqyatWQMY'
            +'IUJ4WMawYcNpI54kgOGhmbRq1J49i8ZsmgeECZgx9DAigckRDaqNlMGAojNm'
            +'0QRWQ5CkSIIQIp0t0IHiyIAjKKowKPJs2bQQQ5MggEaNo7MGI3QsdJaAlw8o'
            +'OZo0seXjSJUFCJY1y7AAgMVo0aRZK8JgAcMFvMTkmKsVShNdiiAsgLasSAaK'
            +'S2d+zLCwwZNjTeYiaQKl8SM7Bjb9YBgigVlm0KY16JCB2rIOv14hodvEUONL'
            +'3AoMyGCtrwwYSpk9NbmsWogB9kZDoWJC0ytDfFIUwMFrMoInIzwgYNYMQAK3'
            +'CDJIGZb4GiQB6QRQIJKpwJYjCSgv/2jwsvnzZdGlQEEC7DqN9wLgMCpwT4oM'
            +'actMkpfdIAGD2rcZwp4Y6aRhYDqQMHKLHlJkENYCljWT2WadLbPAG1wAwwMP'
            +'JBiYRjpwWLHgACHwpZ8zgv2gQzN9gfMPOQTcUwANadDgigYp3LKGMW4tk0EH'
            +'DUwzUxIwyFDEMtZkMMAhMjrxHg1XgJFCGS3QAQCSOvygXFprMTDCMtIwsMQM'
            +'GFgyRDpoapGCFfS8wYBII4RQhFJcstXBMtAkYMwMaVTwhwDYuaEAGwPocGV0'
            +'QL40ZBEhwIBeCEfMEIE4gABBgwA0BBADLwt49kOjSlUzJAwZNLCMBzpIsUIb'
            +'atSgRB+tZP8qhaFgktVAMzBBgwBJT4QFAwQX3EOGP4ggUoM/O8wwgAzOLAPA'
            +'X8oxBc1TC4TAUAJLoFKAGpHI00cNCggDCIlhfTonAhjxRxs0t6FSiDqD0ECK'
            +'EsKkcAC5nzEAgDXSxMScc9BJ5wQl/ohgcAVgWMKggxZGCNMzsjkXnjS3MXFA'
            +'JHEYLMIayojS4IMO+0vtf9EwMIALKcgTyQ25cNFxEySamMB+MU3bQLXXGhOB'
            +'OkooYUQBeojSxD5LhLdMCOM5w9QzE3JW1AK/zOCAApZ0DMxWEaBwZzQ/Brl0'
            +'0xm8FTUNJ5QwDBS6vEJBDJs4Ko0OyU3zNbXWWvjGDDSY0Eg5oVD/IUAaMYDj'
            +'KAJweyB3Rur+Rw22RpjRggHbNHLN32w7Ck3Xh0PsjMR4MnDEFXy88EIbZphR'
            +'KVB3Hp300v/SxsxtWhhBSSHBKHAKI4yQUbRnJz4c8bqeb7ADH8W84MkVizCy'
            +'CIn4QXiZyJxX4znegeDAhSc1LFLJIg0220HImkcvJt6Q9GDwBow4YUP3y4yg'
            +'L67+mhceNJ67wsEfVGjMyC4csN/B+74zj1ted4ROgMALVziAE7BRCUYIwn/g'
            +'a90AbwMCQYBgeCpQwPbIsCyQPQ9i8uvcEeZwAEEYwROWYEclOrGGIzAgGstg'
            +'wMxeIrL+hKdkYwoEELgwB0F4ohK7OMEv/3okg9UhbjbhWdyYaAAJE1zjGhQw'
            +'AC5iAAFHMUMHQMqcum4ophj4gQkmCCMk0hEAKdDBUdNATrQQF8LXDaAFRgDB'
            +'E4FggzxMUXDoKdxS2Agw9CjphGTogThYsId6XGFTX4IGFg3HOvPcaSxSUIEK'
            +'UCGCF+xiF3voBDbe0COkkaeRznmkdC7ZCBGooA51MIUqHDEABqikd/HrIwJk'
            +'IAUWlKEHodgDC1rQiDqo4mMN+yB/FkAyz6liD3soBgtYEApNSLJB0/gM+MDm'
            +'GdBgwxveqIMK9tAIFbxgD6sJy/c+qCteRRMGm4iBE0zRDhDM4xovUIEp8PU/'
            +'s/TrGSnSQRKclf+qGbRgDoDgTQvWcAd8uW9O98znPhuQqgBcqomQiMAMlJUB'
            +'FvkFNuiiRjkjwiIAPEEKDhVAGE1AATJK4QlXcsYTEpUrzXCGLyOAgCLCsI4w'
            +'aMMcVAiDBEgQAxT0yCT76tcw65aAN8AiFbEoxShGgQxZrIMecPAFa5wFLXT9'
            +'bn63wYIELICJpCKDFU59wQ3alse4QUOCfhwAPbCgVUl0FRmrCMMBYPGLOz2j'
            +'iJ/8FwPu5AzprAAf+bhGBaKQjVSUQhawgMcdUodXpemVr9KBwxkw4MRr9EAS'
            +'qRiFAW7QD7dh0Wutu9M0lBQABI30GuKQACsCsJrCVLUaaJ3lAK7ABHH/nIAK'
            +'T7QODWZgjASo5H8IhW0bbzOLXiSiFxaQxAp8cAxNQeBLXEsaTIb5n2cUNQgF'
            +'cIcdZpGI7jqBADGwEpa0tEewwfAHm8gDE9CBD+y6YxZXcEUMnrCQZ2EUIxt9'
            +'AosakIFIzSAK4iBBe93Ri1ntEyFF4FdMBEMqUzWDASiQAp8ulYcVHAIHDWKR'
            +'+z44qgwcKgEQkHAAPiQAJ3ABAxDk8K4abJSqiPhD6eCHEhQQzmDCj2m7UtE+'
            +'PZCBJZAiDnGgAZpoAAoHSCEEzZumSzMgEhiAwwZoEIYrbAAoXOzWhSIBKg01'
            +'dzOivoEThWiDMPhQAUisgAkzwHJ+LLPlqy7D/42o4EQ89EEJF1zjE/oYAvNs'
            +'HMBQLqOvUqAHKk4why/goBG36Ma9MhBN5904tH/OQAzmQAkRGAAd4hCBCzQw'
            +'CfZt+NGOjLQUgOCEPHSBEkQQQSOI0YZZafh994Q0oNnwgAmQgBuTSAYc7CCE'
            +'BrUGwQoGoZ9HK4VCBGEC8SCCHOTwATuwIcPLKNK50iVA9MhgAGtYQzEecABu'
            +'8OEDlnDDalrDXy3JjSPVRsBthuCCFUyAEsToxge6oYjW+rEs/BJuHyk2gNLq'
            +'rREUEMcNcKEsHTiqfa9hJKT5zQQfUKAHjeiBCTBVRggkgEWjLYtFYnsbMJAD'
            +'GFAoAQZwUIECKQs5DP8pEkY5jm0+EOBqxbBEMTSAhQDcwRiEEYsap8HyCeiD'
            +'CIUgRxMmcIACfIAGhiAAOL6kuv1Um9+4OAEHvkAJHgDDEGvgQzoeQQ6fMkSG'
            +'Tt/3bfwN8W344BVbCEI6nCCK54on7Ofhdys4cNtG2L0Hk6PBGbaA0rIajuWu'
            +'+MIDePAAMWAgAiYoUE9DEu2/xCbdtxGCK5wwAR4QYAKWIB5Fr8SuCEkDrQx3'
            +'xQHyUXkYEYAHM/iFbxtPEbmhlYABIMUZ2PCFSxCAAIXgROUAZJl8vx5S5IM4'
            +'FZhwiC2sYL6mQpW5oYHuPhJQHLkon8HOcYBuGGBWv5ZTqKjx+yN4wQsHEAL/'
            +'Gy4QBT4Qwwme1lew0Uq/I5hBAwf4gCtoQQQ+cEMDwKzno5G4jMUZgwga4AqE'
            +'8AFtUH/cQAT2IU6wVkPEJDaS5QbvQIBEQAR2oGcyEE3mkgT3ZDM48xm8EAMf'
            +'AgnXMCkcYAOsNVX2tX0cKAMMEVMgiCCWJXECUEZ9p1IowXPRwIF1swAoEANs'
            +'4ACDEAiRAwZfMAQ9lTpApWDUtQzWZQwbUAOIMAV+sAMfAAYTyFoyYFGOZ1X8'
            +'Jz1HsAM1kAVTMAWEUAOnoAHd0AeDQFaEY1ZbtAw49AFhOIZjoAQ1MGZ9MAZD'
            +'9HYvMVQM0QG8AIZZEAdFVoYKAAZKMAaKkABFoWWY/+FSOhAWz7IBWhAJI1Yj'
            +'M3YKWOAA45A6nqQoK5YBR1INUdETAyAFMTADflAD7BADS/ANpjINnyU3iyJD'
            +'DNEM7pMBTwAOvGAMAzAAQMALf5FyVcV8BQEACzBVSAIDIwAhIZABOqADGTAR'
            +'KhEmCTBt6LYZT2Aqb+YBAAADMPADI9ABHQADDcAXfbFS9oQWx5iM+4QeDVAE'
            +'4DiPAOAB+AGHI9A1Z1GLCeAZ0lAE3/McCzACMFAE9tgQMPAE+IYuDCaKTIgQ'
            +'uwgOVSCNbfEDDXCPzsAALREtTROJy9AAMuACdyAFJDkAxoACdJABDPADLPKR'
            +'K3UrzJA4b8EL9LAGdkAEc/9wA3AQA1IwAL8gEdzYAdq3HKEmW05gCXZQC6zG'
            +'DVagBa1wA77ACwzQGkmgR3o1GVUpBahQC3YwCWDADcQABlegBmR5Cm7XdM6g'
            +'FoziKB5QBTFACbVQC23QBsRAC+GCBmpgBWqwZ46mlo3ykXQQA5bAlRTAAUJw'
            +'Clegl2hAC2qAfe0Da2vxlw3glsFQC7QgAl3QBVdAC1GABWuCBvO1EDAwFNag'
            +'V2z5BDFgB2CJmV1wCimQmW2ABlYQA1UgmnJSms3hJWKRKpPQBnaQC5lpBVYA'
            +'m2gABrQpmgC0ObTBb23ADWI5BxpAC1YgDhRgBZmgATGgA63xaTp4LUswB6dA'
            +'C+L/aQUpkAlzmQJggAUdZGNgoxIjgAKKIAfckAlrgp5zSQwaMAecxIcb5ZG/'
            +'EgMtwwT0QA9R8AcaYAQaYAY30HfNoEf5dU7plAYCEAW5UGYC8AdDMAQ3gAKr'
            +'FyfnkhkkoQP48QMQEAMRYAM4YALXkQ6Z4oqlcm8wCTZP8wsGUAiFQAlMcB2B'
            +'kAYzIAWb0AFFoXLRsoTU4DmfUAyFUACo4Dct4AIFdyXMQBbr2DoTc23FcKQ2'
            +'Sln6wAQ2sBo7liWMxH2hBmgFcAknQAKFgAHXgAqowATj5hrTJqZ+1lcxUAyX'
            +'IAIYwAkY0AgXQAn64GvRdpuxNqbScQEFgAFdcAmcoGqF/7AG0PZpfZYAkCUF'
            +'MlIAJXAJxZAMx1AIf5oB3hNBoUZsZVAG91CqBfAJisoJ6+lokQod10aq90AA'
            +'BUAAo3oPJOBCntEW+8FH56FuA1ACecAF6DABD1CsD4ADe7gMeKVFTzd26fBv'
            +'muADPhABiNR/mANKcXcbh8AFmgBxkkM5vPAl1HCtvDpBR3B5eEB4XJAHmhAI'
            +'qeeJ46FFynlDekIAeDABxGoIPKAMyjABuxND0nVEXdaCm2Cv+Fp5ysAD+Eoi'
            +'WaZkvNIa1sAAvGAAF3AIp3d5D4AO0MRnC0YTjJI6HpAAT2AMEhYBj4AHeYBi'
            +'nipNH5SNHaADR4InzlEFR2CiJZHwCD6wGtE0TjemUR67EyMQFrXBKBH2CFuw'
            +'BW7ySuCzER3hAQD5jDAgtEmQAOCAA2KgC1UwGWjJDBkhE9IwDUlwENUyjOgR'
            +'JzoQDgvAIs2wc0vDhAPBDAjQDB4gtmRxj83RAEIrlHHaEAKRg9IQt94YJwrh'
            +'ECn3WWdRFHzbt9Dwt9ZwEAmgA0ljEDtxjUrRtgEBADs=')

newButton = tk.Button(root,image=img00)
t = str(img00.width()) + ' wide x ' + str(img00.height()) + ' high'
newButton.pack()
tk.Label(root,text='The image is\n'+t).pack()
root.mainloop()    #comment this out to run from IDLE
