# _ File: graph_relationship.py__________________________________________________________________________________
#  Graphical LINK for entity relationship, generated by ATOM3
# ______________________________________________________________________________________________________
from graphLink import *
from stickylink   		import *
from ATOM3Boolean 		import *
from ATOM3Integer		import *
from ATOM3Appearance		import *
from ATOM3String		import *
from widthXfillXdecoration      import *
from linkEditor import *

class graph_ERrelationship(graphLink):

   def __init__(self, xc, yc, semObject = None ):
      self.semanticObject = semObject
      self.semObject = semObject

      self.le=linkEditor(self,semObject, "relationship")
      self.le.FirstLink= stickylink()
      self.le.FirstLink.arrow=ATOM3Boolean()
      self.le.FirstLink.arrow.setValue((' ', 0))
      self.le.FirstLink.arrow.config = 0
      self.le.FirstLink.arrowShape1=ATOM3Integer(6)
      self.le.FirstLink.arrowShape2=ATOM3Integer(6)
      self.le.FirstLink.arrowShape3=ATOM3Integer(6)
      self.le.FirstLink.decoration=ATOM3Appearance()
      self.le.FirstLink.decoration.setValue( ('relationship_1stLink', self.le.FirstLink))
      self.le.FirstSegment= widthXfillXdecoration()
      self.le.FirstSegment.width=ATOM3Integer(2)
      self.le.FirstSegment.fill=ATOM3String('black')
      self.le.FirstSegment.decoration=ATOM3Appearance()
      self.le.FirstSegment.decoration.setValue( ('ERrelationship_1stSegment', self.le.FirstSegment))
      self.le.Center=ATOM3Appearance()
      self.le.Center.setValue( ('ERrelationship_Center', self.le))
      self.le.SecondSegment= widthXfillXdecoration()
      self.le.SecondSegment.width=ATOM3Integer(2)
      self.le.SecondSegment.fill=ATOM3String('black')
      self.le.SecondSegment.decoration=ATOM3Appearance()
      self.le.SecondSegment.decoration.setValue( ('ERrelationship_2ndSegment', self.le.SecondSegment))
      self.le.SecondLink= stickylink()
      self.le.SecondLink.arrow=ATOM3Boolean()
      self.le.SecondLink.arrow.setValue((' ', 1))
      self.le.SecondLink.arrow.config = 0
      self.le.SecondLink.arrowShape1=ATOM3Integer(14)
      self.le.SecondLink.arrowShape2=ATOM3Integer(18)
      self.le.SecondLink.arrowShape3=ATOM3Integer(4)
      self.le.SecondLink.decoration=ATOM3Appearance()
      self.le.SecondLink.decoration.setValue( ('ERrelationship_2ndLink', self.le.SecondLink))
      self.le.FirstLink.decoration.semObject=self.semObject
      self.le.FirstSegment.decoration.semObject=self.semObject
      self.le.Center.semObject=self.semObject
      self.le.SecondSegment.decoration.semObject=self.semObject
      self.le.SecondLink.decoration.semObject=self.semObject
      graphLink.__init__(self, xc, yc, self.le,semObject)
